export default {
  roots: ['<rootDir>/src'],
  collectCoverageFrom: ['<rootDir>/src/**/*.ts'],
  testRegex: '.spec.ts$',
  coverageDirectory: 'coverage',
  coverageProvider: 'v8',
  collectCoverage: true,
  coverageReporters: ['json-summary', 'lcov', 'text'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  coveragePathIgnorePatterns: [
    '/src/migrations/',
    '/src/health/',
    '/src/main.ts',
    '/src/auth/auth.guard.ts',
    'app.module.ts',
    'config.schema.ts',
    '.+\\.module.ts$',
    '.+\\.dto.ts$',
    '.+\\.interceptor.ts$',
    '.+\\.decorator.ts$',
    '.+\\.strategy.ts$',
    '.+\\.interface.ts$',
    '.+\\.resolver.ts$',
    '.+\\.test.ts$',
    '.+\\.mock.ts$',
    '.+\\.entity.ts$',
    '.+\\.adapter.ts$',
  ],
  testEnvironment: 'node',
  transform: {
    '.+\\.ts$': 'ts-jest',
  },
};
